### ISSUE TITLE
RedPanda hardening

### ISSUE THREAD

**Issue by entlein** [k8sstormcenter/honeycluster#9]
The current redpanda deployment is insecure, with unauthenticated clients.
The redpanda/(rke2)values.yaml should be reviewed and altered such that the default settings are acceptable from a security first standpoint, as long as this doesn't not lead to a massively more complicated setup.

**Comment by pjoomen** [comment]
I plan on looking into the redpanda deployment in the coming days.

**Comment by entlein** [comment]
At KCD Munich we learnt of a way we can avoid  red-panda, which I d much prefer since it is the heaviest piece at the moment. So I suspect it will be deprecated at some soonish point
